routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});



Route::get('/clear-cache', function () {
    $exitCode = Artisan::call('cache:clear');
    //   $exitCode = Artisan::call('optimize');
    //     $exitCode = Artisan::call('route:cache');
    $exitCode = Artisan::call('route:clear');
    $exitCode = Artisan::call('view:clear');
    $exitCode = Artisan::call('view:cache');
    $exitCode = Artisan::call('config:cache');
    // return what you want
});

Auth::routes();
Route::get('/', 'HomeController@baseUrl')->middleware('referral')->name('');
Route::get('/pricing', 'PricingController@index')->name('pricing');

// Route::get('create_paypal_plan', 'PaypalController@create_plan');

Route::get('/subscribe/paypal', 'PaypalController@paypalRedirect')->name('paypal.redirect');
Route::get('/subscribe/paypal/return', 'PaypalController@paypalReturn')->name('paypal.return');
// Route::get('delete_paypal_plan', 'PaypalController@delete_plan');

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', 'PricingController@index')->name('pricing');
    //  Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('keywords', 'KeywordController', ['only' => ['destroy', 'store']]);

    /** PayPal Subscription */
    Route::get('/subscribe/{id}/paypal', 'SubscriptionController@paypalRedirect')
        ->name('paypal.redirect');
    Route::get('/subscribe/{id}/paypal/return', 'SubscriptionController@paypalReturn')
        ->name('paypal.return');
    Route::get('/subscribe/{id}/paypal/cancel', 'SubscriptionController@paypalCancel')
        ->name('paypal.cancel');

    /** Stripe Subscription */
    Route::get('/subscribe/{id}/stripe', 'SubscriptionController@stripeRedirect')
        ->name('stripe.redirect');
    Route::post('/subscribe/stripe', 'SubscriptionController@stripeSubscribe')
        ->name('stripe.subscribe');
    Route::post('/subscribe/stripe/trial', 'SubscriptionController@stripeTrial')
        ->name('stripe.trial');
    Route::get('/subscribe/{id}/stripe/cancel', 'SubscriptionController@stripeCancel')
        ->name('stripe.cancel');

    Route::resource('subscriptions', 'SubscriptionController');

    Route::group(['middleware' => ['admin'], 'prefix' => 'admin'], function () {
        Route::get('/', 'Admin\HomeController@index')->name('admin.index');
        Route::get('/download-users-email', 'Admin\HomeController@genearateUserEmailCSV')->name('admin.index.download');
        Route::group(['middleware' => ['superAdmin'], 'prefix' => 'billing'], function () {
            Route::resource('plans', 'Admin\AdminPlanController');
        });
    });
});

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>
                <a href="{{ url('subscribe/paypal') }}"><img src="/images/paypal-btn.png"></a>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pricing.blade.php
@extends('layouts.main')

@section('content')
<div class="row">
    <div class="col-md-8 col-md-offset-2 pt-5">
        <div style="color: #fff; font-size: 14px; margin-bottom: 50px;">
            1. Setup your Keywords by doing an Upwork Search
            and taking the RSS link. <br>
            2. To get more keywords, refer your friends to the app. <br>
            3. Get the job Notifications for your keywords from our mobile app <br>
        </div>
        @foreach (auth()->user()->all_keywords() as $keyword)
        <div class="each-keyword">
            <div class="del-btn">
                <form action="{{ route('keywords.destroy', $keyword->id) }}" method="POST">
                    @method('DELETE')
                    @csrf
                    <button type="submit" style="">
                        <i class="far fa-trash-alt"></i>
                    </button>
                </form>
            </div>
            <div class="keyword-name">
                {{ $keyword->keyword }}
            </div>
            <div class="keyword-info">
                {{ Str::limit($keyword->rss, 25) }}
            </div>
        </div>
        @endforeach

        @if (auth()->user()->all_keywords()->count() != auth()->user()->getAmmountOfKeywords() and auth()->user()->all_keywords()->count() < auth()->user()->getAmmountOfKeywords())
            <div>
                <form method="POST" action="{{ route('keywords.store') }}">
                    @csrf
                    <div class="row">
                        <div class="col-xs-3">
                            <div class="form-group mb-0">
                                <input type="text"
                                    class="form-control website-form-control @error('keyword') is-invalid @enderror"
                                    id="keyword" placeholder="Keyword" name="keyword" style="height: 46px;">
                                @error('keyword')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>
                        <div class="col-xs-7">
                            <div class="form-group mb-0">
                                <input type="text"
                                    class="form-control website-form-control @error('rss') is-invalid @enderror"
                                    id="rss" placeholder="UpWork RSS Link" name="rss" style="height: 46px;">
                                @error('rss')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>
                        <div class="col-xs-2">
                            <button type="submit" style="width: 46px;height: 46px;line-height: 46px;padding: 0;"
                                class="btn btn-default website-form-button">+</button>
                        </div>
                    </div>
                </form>
                @if (session('success'))
                <div class="alert alert-success mt-4" role="alert">
                    {{ session('success') }}
                </div>
                @endif
            </div>
            @endif

            <div style="color: #09ee6a; font-size: 14px; margin-top: 40px; text-align: center;">
                Download Our App <br>
                After setting your keywords <br>
                <a href="#">
                    <img class="img-fluid mt-4 mr-4" src="{{ asset('assets/images/google_play.png') }}" alt="">
                </a>
                <a href="#">
                    <img class="img-fluid mt-4" src="{{ asset('assets/images/apple_store.png') }}" alt="">
                </a>
                <iframe class="mt-5" width="560" height="315" src="https://www.youtube.com/embed/6HosPjdOwkI" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
    </div>
</div>
@endsection

resources/views/pricing_bc.blade.php
@extends('layouts.main')

@section('content')
<div class="row">
    <div class="col-md-8 col-md-offset-2">

        <div class="text-center main-text">
            <p style="margin-top: 10px;"><b>Add your keywords</b></p>
        </div>

        <div class="panel panel-login">
            <div class="row m-0">
                <div class="col-xs-10 col-xs-offset-1 py-5">

                    @foreach (auth()->user()->keywords() as $keyword)
                    <div class="row each-keyword">
                        <div class="col-xs-3">
                            <h1 class="m-0" style="line-height: 46px;">{{ $keyword->keyword }}</h1>
                        </div>
                        <div class="col-xs-7 py-1">
                            <h3 class="m-0" style="line-height: 46px;overflow: hidden;">{{ $keyword->rss }}</h3>
                        </div>
                        <div class="col-xs-2">
                            <form action="{{ route('keywords.destroy', $keyword->id) }}" method="POST">
                                @method('DELETE')
                                @csrf
                                <button type="submit"
                                    style="width: 46px;height: 46px;line-height: 46px;padding: 0;font-size: 14px;background: #a22e2e; color: #fff"
                                    class="btn btn-default website-form-button">Del</button>
                            </form>
                        </div>
                    </div>
                    @endforeach

                    <form method="POST" action="{{ route('keywords.store') }}">
                        @csrf
                        <div class="row">
                            <div class="col-xs-3">
                                <div class="form-group mb-0">
                                    <input type="text"
                                        class="form-control website-form-control @error('keyword') is-invalid @enderror"
                                        id="keyword" placeholder="Keyword" name="keyword">
                                    @error('keyword')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-xs-7">
                                <div class="form-group mb-0">
                                    <input type="text"
                                        class="form-control website-form-control @error('rss') is-invalid @enderror"
                                        id="rss" placeholder="UpWork RSS Link" name="rss">
                                    @error('rss')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-xs-2">
                                <button type="submit" style="width: 46px;height: 46px;line-height: 46px;padding: 0;"
                                    class="btn btn-default website-form-button">+</button>
                            </div>
                        </div>
                    </form>
                    @if (session('success'))
                    <div class="alert alert-success mt-4" role="alert">
                        {{ session('success') }}
                    </div>
                    @endif
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-8 col-md-offset-2">

        <div class="text-center main-text">
            <p style="margin-top: 10px;"><b>Select Your Plan</b></p>
        </div>

        <div class="panel panel-login">

            <div class="row">
                @foreach ($plans as $plan)
                <div class="col-xs-4">
                    <div class="plan" id="basic">
                        <div class="plan-heading">
                            <div class="text-center">
                                {{ $plan->name }}
                            </div>
                        </div>

                        <!--<div class="pull-left">{{ $plan->description }}</div>-->


                        <div class="plan-price">
                            <div class="text-center">
                                @if ($plan->is_free)
                                <b>
                                    Free
                                </b>
                                @else
                                <b>
                                    {{ $plan->currency }} {{ $plan->amount }} / {{ $plan->frequency }}
                                </b>
                                @endif
                            </div>
                        </div>

                        <div class="plan-keyword">
                            <div class="text-center" style="color: grey;">
                                {{ $plan->keyword_limit }} {{ __('Keyword(s)')}}
                            </div>
                        </div>
                        <div class="text-center">
                            @guest
                            {{-- 
                                <a class="form-control btn btn-upgrade" href="{{ route('paypal.redirect', $plan->paypal_plan_id) }}">{{ __('Upgrade Now') }}</a><br />
                            --}}
                            <a class="form-control btn btn-upgrade" href="#">{{ __('Upgrade') }}</a><br />
                            <a class="form-control btn btn-upgrade" href="#">{{ __('Upgrade') }}</a><br />
                            @else
                            @if (
                            Auth::user()->subscription() and
                            Auth::user()->subscribed('default', $plan->stripe_plan_id)
                            )
                            <a class="form-control btn btn-upgrade" href="#">{{ __('Current') }}</a><br />
                            <a class="form-control btn btn-upgrade" style="font-size:8px!important;"
                                href="{{route('stripe.cancel', Auth::user()->subscription()->stripe_plan	)}}">{{ __('Cancel') }}</a><br />
                            @else
                            @if ($plan->is_free)
                            <a class="form-control btn btn-upgrade"
                                href="{{ route('stripe.redirect', $plan->stripe_plan_id) }}">{{ __('Select') }}</a>
                            @else
                            <a class="form-control btn btn-upgrade"
                                href="{{ route('stripe.redirect', $plan->stripe_plan_id) }}">{{ __('Upgrade') }}</a><br />
                            {{-- <a class="form-control btn btn-upgrade"
                                href="{{ route('stripe.redirect', ['id' => $plan->stripe_plan_id, 'try_out_trial' => 'true']) }}">{{ __('Try out trial for 14 days') }}</a><br />
                            --}}
                            @endif
                            @endif

                            @endguest
                            <!--<button class="form-control btn btn-upgrade">Upgrade</button>-->
                        </div>
                    </div>
                </div>
                @endforeach
                <!--                <div class="col-xs-4" style="padding-left:0px!important;padding-right:0px!important;">
                                    <div class="plan active" id="standard">
                                        <div class="plan-heading">
                                            <div class="text-center">
                                                Basic
                                            </div>
                                        </div>
                                        <div class="plan-price">
                                            <div class="text-center">
                                                $4.99/Mo
                                            </div>
                                        </div>
                
                                        <div class="plan-keyword">
                                            <div class="text-center">
                                                1 keyword
                                            </div>
                                        </div>
                                        <div class="text-center">
                                            <button class="form-control btn btn-upgrade">Upgrade</button>
                                        </div>
                                    </div>
                                </div>
                
                                <div class="col-xs-4" style="padding-left:0px!important;padding-right:12px!important;">
                                    <div class="plan" id="premium">
                                        <div class="plan-heading">
                                            <div class="text-center">
                                                Basic
                                            </div>
                                        </div>
                                        <div class="plan-price">
                                            <div class="text-center">
                                                $4.99/Mo
                                            </div>
                                        </div>
                
                                        <div class="plan-keyword">
                                            <div class="text-center">
                                                1 keyword
                                            </div>
                                        </div>
                                        <div class="text-center">
                                            <button class="form-control btn btn-upgrade">Upgrade</button>
                                        </div>
                                    </div>
                                </div>-->
            </div>

            <div class="row justify-content-center mt-5">
                <div class="col-md-6 col-lg-4">
                    <div class="plan">
                        <div class=" text-center main-text p-3">
                            <b class="text-white">Referr Someone</b>
                            <input type="text" class="form-control bg-white text-center my-2"
                                value="{{ auth()->user()->affiliate_id }}" readonly>
                            <input type="text" class="form-control bg-white text-center my-2"
                                value="{{ auth()->user()->getReferralLink() }}"
                                style="text-overflow: ellipsis;overflow: hidden;white-space: normal;" readonly>
                            <div class="my-5">
                                <b class="text-white">Total Referral Points:</b>
                                <b class="text-white">{{ auth()->user()->getAmmountOff() }}</b>
                            </div>
                        </div>
                    </div>
                </div>
            </div>



            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="text-center">

                            <p class="custom-text"> Contact For Custom Quantity</p>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body">
                <p>One fine body&hellip;</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

@endsection

resources/views/pricing_bk.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        @foreach ($plans as $plan)
        <div class="col-sm-4 col-xs-12">
            <div class="card">
                <div class="card-header">
                    <div class="pull-left">{{ $plan->name }}</div>
                </div>

                <div class="card-body">
                    <div class="pull-left">{{ $plan->description }}</div>
                    <div class="pull-left">{{ $plan->keyword_limit }} {{ __('Keyword(s)')}}</div>
                    <div>{{ $plan->amount }}{{ $plan->currency }} per {{ $plan->frequency_interval }}{{ $plan->frequency }}</div>
                </div>
                <div class="card-footer">
                    <div class="col-xs-6">
                        @guest
                        <a class="btn btn-primary" href="{{ route('paypal.redirect', $plan->paypal_plan_id) }}">{{ __('Upgrade Now') }}</a><br />
                        @else
                            @if (Auth::user() and Auth::user()->subscription() and Auth::user()->subscription()->plan_id == $plan->id)
                            <a class="btn btn-success" href="#">{{ __('Current Plan') }}</a><br />
                            @else
                            <a class="btn btn-primary" href="{{ route('paypal.redirect', $plan->paypal_plan_id) }}">{{ __('Update Now') }}</a><br />
                            @endif
                        @endguest
                    </div>
                </div>
            </div>
        </div>
        @endforeach
    </div>
</div>
@endsection

resources/views/welcome1.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">

        <!-- Styles -->
        <style>
            body {
    background-color: #000000;
    font-family: Roboto,sans-serif;
    font-weight: 400;
    margin-bottom: 150px;
    padding-top: 0;
}



.logo{padding-top:10px;color:#09ef6b;}

.hover{text-decoration:none!important;}

.main-text{color:white;font-size:12px;padding-top:5px;padding-bottom:5px;}

.custom-text{color:#119747;font-size:12px;padding-top:260px;}

.panel {
    background-color: #1a1a1a!important;border-radius:0px!important;
    }

.panel-body {padding-top:50px;}

.fields{padding-bottom:50px;}

.plan{border:1px solid #111111;margin-left:5px;margin-right:5px;border-radius: 4px;padding-bottom: 10px;margin-top:10px;}

.plan:hover{border:1px solid #1CB94E;}

.plan-heading{color:#FFFFFF;font-size:12px;padding-top:20px;}
.plan-price{color:#FFFFFF;font-size:15px;padding-top:5px;}
.plan-keyword {color:#FFFFFF;font-size:12px;margin-top:5px;}
.panel-login {
	-webkit-box-shadow: 0px 2px 3px 0px rgba(0,0,0,0.2);
	-moz-box-shadow: 0px 2px 3px 0px rgba(0,0,0,0.2);
	box-shadow: 0px 2px 3px 0px rgba(0,0,0,0.2);
}
.panel-login>.panel-heading {
	color: #00415d;
	background-color: #1a1a1a;
	text-align:center;
}
.panel-login>.panel-heading a{
	text-decoration: none;
	color: #666;
	font-weight: bold;
	font-size: 12px;
	-webkit-transition: all 0.1s linear;
	-moz-transition: all 0.1s linear;
	transition: all 0.1s linear;
}
.panel-login>.panel-heading a.active{
	padding-left: 40px;
	padding-right: 40px;
	padding-bottom: 21px;
	border-bottom: 2px solid #109847;
	color: #109847;
	font-size: 15px;
}

.panel-login input[type="text"],.panel-login input[type="email"],.panel-login input[type="password"] {
	background-color: #0d0d0d;
	height: 45px;
	border: 1px solid #ddd;
	font-size: 12px;
	-webkit-transition: all 0.1s linear;
	-moz-transition: all 0.1s linear;
	transition: all 0.1s linear;
}
.panel-login input:hover,
.panel-login input:focus {
	outline:none;
	-webkit-box-shadow: none;
	-moz-box-shadow: none;
	box-shadow: none;
	border-color: #ccc;
}
.btn-login {
	background-color: #09ef6b;
	outline: none;
	color: #fff;
	font-size: 12px;
	height: auto;
	font-weight: normal;
	text-transform: uppercase;
	
}

.btn-login:hover,
.btn-login:focus {
	color: #fff;
	background-color: #000000;
	
}
.forgot-password {
	font-size:12px;
	color:#119747;
}
.forgot-password:hover,
.forgot-password:focus {
	
	color: #666;
}

.btn-register {
	background-color: #1CB94E;
	outline: none;
	color: #fff;
	font-size: 12px;
	height: auto;
	font-weight: normal;
	padding: 14px 0;
	text-transform: uppercase;
	border-color: #1CB94A;
}
.btn-register:hover,
.btn-register:focus {
	color: #fff;
	background-color: #1CA347;
	border-color: #1CA347;
}

.btn-upgrade {
	width:80%;
	margin-left:5px;
	margin-right:5px;
	margin-top:5px;
	background-color: #1CB94E;
	outline: none;
	color: #fff;
	font-size: 12px;
	height: auto;
	font-weight: normal;
	text-transform: uppercase;
	border-color: #1CB94A;
}

.btn-upgrade:hover,
.btn-upgrade:focus {
	width:80%;
	margin-left:5px;
	margin-right:5px;
	color: #fff;
	background-color: #1CA347;
	border-color: #1CA347;
}
        </style>
    </head>
    <body>
        <div class="flex-center position-ref full-height">
            <div class="top-left links">
                <a href="{{ route('pricing') }}">{{ __('Pricing') }}</a>
            </div>
            @if (Route::has('login'))
                <div class="top-right links">
                    @auth
                        <a href="{{ url('/home') }}">Home</a>
                    @else
                        <a href="{{ route('login') }}">Login</a>

                        @if (Route::has('register'))
                            <a href="{{ route('register') }}">Register</a>
                        @endif
                    @endauth
                </div>
            @endif

            <div class="content">
                <div class="title m-b-md">
                    Welcome to Upwork Job Tracker
                </div>
            </div>
        </div>
    </body>
</html>