routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});



Route::get('/clear-cache', function () {
    $exitCode = Artisan::call('cache:clear');
    //   $exitCode = Artisan::call('optimize');
    //     $exitCode = Artisan::call('route:cache');
    $exitCode = Artisan::call('route:clear');
    $exitCode = Artisan::call('view:clear');
    $exitCode = Artisan::call('view:cache');
    $exitCode = Artisan::call('config:cache');
    // return what you want
});

Auth::routes();
Route::get('/', 'HomeController@baseUrl')->middleware('referral')->name('');
Route::get('/pricing', 'PricingController@index')->name('pricing');

// Route::get('create_paypal_plan', 'PaypalController@create_plan');

Route::get('/subscribe/paypal', 'PaypalController@paypalRedirect')->name('paypal.redirect');
Route::get('/subscribe/paypal/return', 'PaypalController@paypalReturn')->name('paypal.return');
// Route::get('delete_paypal_plan', 'PaypalController@delete_plan');

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', 'PricingController@index')->name('pricing');
    //  Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('keywords', 'KeywordController', ['only' => ['destroy', 'store']]);

    /** PayPal Subscription */
    Route::get('/subscribe/{id}/paypal', 'SubscriptionController@paypalRedirect')
        ->name('paypal.redirect');
    Route::get('/subscribe/{id}/paypal/return', 'SubscriptionController@paypalReturn')
        ->name('paypal.return');
    Route::get('/subscribe/{id}/paypal/cancel', 'SubscriptionController@paypalCancel')
        ->name('paypal.cancel');

    /** Stripe Subscription */
    Route::get('/subscribe/{id}/stripe', 'SubscriptionController@stripeRedirect')
        ->name('stripe.redirect');
    Route::post('/subscribe/stripe', 'SubscriptionController@stripeSubscribe')
        ->name('stripe.subscribe');
    Route::post('/subscribe/stripe/trial', 'SubscriptionController@stripeTrial')
        ->name('stripe.trial');
    Route::get('/subscribe/{id}/stripe/cancel', 'SubscriptionController@stripeCancel')
        ->name('stripe.cancel');

    Route::resource('subscriptions', 'SubscriptionController');

    Route::group(['middleware' => ['admin'], 'prefix' => 'admin'], function () {
        Route::get('/', 'Admin\HomeController@index')->name('admin.index');
        Route::get('/download-users-email', 'Admin\HomeController@genearateUserEmailCSV')->name('admin.index.download');
        Route::group(['middleware' => ['superAdmin'], 'prefix' => 'billing'], function () {
            Route::resource('plans', 'Admin\AdminPlanController');
        });
    });
});

app/Plan.php
<?php

namespace App;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Eloquent\Model;

class Plan extends Model
{
    protected $fillable = [
        'name', 'description', 'paypal_plan_id', 'type',
        'frequency_interval', 'cycles',
        'amount', 'currency', 'keyword_limit', 'is_default',
    ];

    /**
     * The "booted" method of the model.
     *
     * @return void
     */
    protected static function booted()
    {
        static::created(function ($plan) {
            // dd($plan->is_default);
            try {
                DB::beginTransaction();
                // Checking if the user is referred by someone
                if ($plan->is_default == 1) {
                    $other_plans = Plan::where([
                        ['id', '!=', $plan->id],
                        ['is_default', '=', 1],
                    ])->get();

                    foreach ($other_plans as $plan) {
                        $plan->is_default = 0;
                        $plan->save();
                    }
                }
                DB::commit();
            } catch (\Throwable $th) {
                DB::rollback();
                throw $th;
            }
        });
    }
}

resources/views/admin/plans/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Create a new Plan') }}</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif
                        @if ($errors = Session::get('errors'))
                            @foreach ($errors->all() as $message)
                                <div class="alert alert-danger">
                                    <span>{{ $message }}</span>
                                </div>
                            @endforeach
                        @endif

                        <form action="{{ route('plans.store') }}" method="POST">
                            @csrf

                            <div class="row">
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <strong>{{ __('Name') }}:</strong>
                                        <input type="text" name="name" class="form-control" placeholder="{{ __('Name') }}">
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <strong>{{ __('Description') }}:</strong>
                                        <textarea class="form-control" style="height:150px" name="description"
                                            placeholder="{{ __('Description') }}">
                                        </textarea>
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <strong>{{ __('Frequency Interval Month') }}:</strong>
                                        <input class="form-control" type="number" name="frequency_interval" value="1"
                                            min="1" max="12" placeholder="{{ __('Frequency Interval Month') }}" />
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <strong>{{ __('Keyword') }}:</strong>
                                        <input class="form-control" name="keyword_limit" type="number" value="1" step="0.01"
                                            placeholder="{{ __('Keyword Count') }}" />
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <strong>{{ __('Amount') }}:</strong>
                                        <input class="form-control" name="amount" type="number" value="10" min="0"
                                            step="0.01" placeholder="{{ __('Amount') }}" />
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" name="isFree" value="1" id="isFree">
                                        <label class="form-check-label" for="isFree">
                                            Free
                                        </label>
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" name="isDefault" value="1"
                                            id="isDefault">
                                        <label class="form-check-label" for="isDefault">
                                            Make Default
                                        </label>
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12 text-right">
                                    <button type="submit" class="btn btn-primary">{{ __('Save') }}</button>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/plans/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Edit Plan') }}{{ $plan->paypal_plan_id }}</div>

                <div class="card-body">
                    @if (session('status'))
                    <div class="alert alert-success" role="alert">
                        {{ session('status') }}
                    </div>
                    @endif
                    @if ($errors = Session::get('errors'))
                    @foreach ($errors->all() as $message)
                    <div class="alert alert-danger">
                        <span>{{ $message }}</span>
                    </div>
                    @endforeach
                    @endif

                    <form action="{{ route('plans.update', $plan->id) }}" method="POST">
                        @csrf
                        @method('PUT')

                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>{{ __('Name') }}:</strong>
                                    <input type="text" name="name" value="{{ $plan->name }}" class="form-control"
                                        placeholder="{{ __('Name') }}">
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>{{ __('Description') }}:</strong>
                                    <textarea class="form-control" style="height:150px" name="description"
                                        placeholder="{{ __('Description') }}">{{ $plan->description }}</textarea>
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>{{ __('Frequency Interval Month') }}:</strong>
                                    <input class="form-control" type="number" name="frequency_interval"
                                        value="{{ $plan->frequency_interval }}" min="1" max="12"
                                        placeholder="{{ __('Frequency Interval Month') }}" />
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>{{ __('Keyword') }}:</strong>
                                    <input class="form-control" name="keyword_limit" type="number" value="1" step="0.01"
                                        placeholder="{{ __('Keyword Count') }}" />
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>{{ __('Amount') }}:</strong>
                                    <input class="form-control" name="amount" type="number" value="{{ $plan->amount }}"
                                        min="0" placeholder="{{ __('Amount') }}" />
                                </div>
                            </div>

                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" name="isFree" value="1" id="isFree"
                                        {{ $plan->is_free ? 'checked' : ''}}>
                                    <label class="form-check-label" for="isFree">
                                        Free
                                    </label>
                                </div>
                            </div>

                            <div class="col-xs-12 col-sm-12 col-md-12 text-right">
                                <button type="submit" class="btn btn-primary">{{ __('Save') }}</button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/plans/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="pull-left">{{ __('Plans') }}</div>
                </div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <table class="table table-bordered">
                        <tr>
                            <th>{{ __('No') }}</th>
                            <th>{{ __('Name') }}</th>
                            <th>{{ __('Price') }}</th>
                            <th>{{ __('Keyword') }}</th>
                            <th width="280px">{{ __('Action') }}</th>
                        </tr>
                        @foreach ($plans as $index => $plan)
                        <tr>
                            <td>{{ $index + 1 }}</td>
                            <td>{{ $plan->name }}</td>
                            <td>{{ $plan->amount }}{{ $plan->currency }} per {{ $plan->frequency_interval }}{{ $plan->frequency }}</td>
                            <td>{{ $plan->keyword_limit }}</td>
                            <td>
                                <form action="{{ route('plans.destroy',$plan->id) }}" method="POST">
                
                                    <a class="btn btn-info" href="{{ route('plans.show', $plan->id) }}">{{ __('Show') }}</a>
                    
                                    {{-- <a class="btn btn-primary" href="{{ route('plans.edit',$plan->id) }}">{{ __('Edit') }}</a>  --}}
                
                                    @csrf
                                    @method('DELETE')

                                    <button type="submit" class="btn btn-danger">{{ __('Delete') }}</button>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </table>
                </div>
                <div class="card-footer">
                    <div class="col-xs-6">
                        <a class="btn btn-primary" href="{{ route('plans.create') }}">{{ __('Create new Plan') }}</a><br />
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/plans/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Show a Plan') }}</div>

                <div class="card-body">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>{{ __('Name') }}:</strong>
                            {{ $plan->name }}
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>{{ __('Description') }}:</strong>
                            {{ $plan->description }}
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>{{ __('Cost') }}:</strong>
                            {{ $plan->amount }}{{ $plan->currency }} per {{ $plan->frequency_interval }} {{ $plan->frequency }}
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <div class="col-xs-12">
                        <a class="btn btn-secondary" href="{{ route('plans.index') }}">Back</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection